"""
Integration Tests for ResonanceOS v6
"""

import unittest
import tempfile
import shutil
from pathlib import Path
from resonance_os import HRV_DIMENSIONS, HumanResonantWriter, HRVProfileManager, HRVExtractor
from resonance_os.api.hr_server import SimpleRequest, hr_generate


class TestIntegration(unittest.TestCase):
    """Test integration between all components"""
    
    def setUp(self):
        """Set up test fixtures"""
        self.temp_dir = Path(tempfile.mkdtemp())
        self.writer = HumanResonantWriter()
        self.profile_manager = HRVProfileManager(self.temp_dir)
        self.extractor = HRVExtractor()
    
    def tearDown(self):
        """Clean up test fixtures"""
        shutil.rmtree(self.temp_dir)
    
    def test_full_pipeline_integration(self):
        """Test complete pipeline from prompt to HRV extraction"""
        prompt = "Test integration prompt"
        
        # Step 1: Generate content
        generated_content = self.writer.generate(prompt)
        self.assertIsInstance(generated_content, str)
        self.assertGreater(len(generated_content), 0)
        
        # Step 2: Extract HRV from generated content
        hrv_vector = self.extractor.extract(generated_content)
        self.assertIsInstance(hrv_vector, list)
        self.assertEqual(len(hrv_vector), 8)
        
        # Step 3: Verify HRV dimensions match
        self.assertEqual(len(hrv_vector), len(HRV_DIMENSIONS))
        
        # Step 4: Save HRV as profile
        self.profile_manager.save_profile("test_tenant", "integration_profile", hrv_vector)
        
        # Step 5: Load and verify profile
        loaded_hrv = self.profile_manager.load_profile("test_tenant", "integration_profile")
        self.assertEqual(loaded_hrv, hrv_vector)
    
    def test_api_writer_integration(self):
        """Test API integration with writer"""
        request = SimpleRequest(prompt="API integration test")
        response = hr_generate(request)
        
        # Verify response structure
        self.assertIsInstance(response.article, str)
        self.assertIsInstance(response.hrv_feedback, list)
        self.assertEqual(len(response.hrv_feedback), 8)
        
        # Verify content was generated by writer
        self.assertIn("Paragraph outline", response.article)
        self.assertIn("HRV feedback", response.article)
        self.assertIn(request.prompt, response.article)
    
    def test_profile_writer_integration(self):
        """Test profile manager integration with writer"""
        # Create and save different profiles
        tech_profile = [0.8, 0.7, 0.9, 0.6, 0.5, 0.4, 0.3, 0.7]
        creative_profile = [0.3, 0.9, 0.8, 0.4, 0.7, 0.8, 0.6, 0.5]
        
        self.profile_manager.save_profile("tech_company", "brand_voice", tech_profile)
        self.profile_manager.save_profile("creative_agency", "brand_voice", creative_profile)
        
        # Verify profiles can be loaded
        loaded_tech = self.profile_manager.load_profile("tech_company", "brand_voice")
        loaded_creative = self.profile_manager.load_profile("creative_agency", "brand_voice")
        
        self.assertEqual(loaded_tech, tech_profile)
        self.assertEqual(loaded_creative, creative_profile)
        
        # Generate content and extract HRV
        content = self.writer.generate("Test content for profile integration")
        content_hrv = self.extractor.extract(content)
        
        # Verify HRV extraction works
        self.assertIsInstance(content_hrv, list)
        self.assertEqual(len(content_hrv), 8)
    
    def test_extractor_writer_integration(self):
        """Test HRV extractor integration with writer"""
        prompts = [
            "Positive and amazing content",
            "Negative and terrible content",
            "Neutral and factual content"
        ]
        
        for prompt in prompts:
            # Generate content
            content = self.writer.generate(prompt)
            
            # Extract HRV
            hrv = self.extractor.extract(content)
            
            # Verify extraction
            self.assertIsInstance(hrv, list)
            self.assertEqual(len(hrv), 8)
            
            # Verify content contains prompt
            self.assertIn(prompt, content)
    
    def test_multi_tenant_integration(self):
        """Test multi-tenant integration"""
        tenants = ["tenant1", "tenant2", "tenant3"]
        profiles = ["profile1", "profile2", "profile3"]
        
        # Create profiles for each tenant
        for i, tenant in enumerate(tenants):
            for j, profile in enumerate(profiles):
                hrv_vector = [0.1 * (i + j + 1)] * 8
                self.profile_manager.save_profile(tenant, profile, hrv_vector)
        
        # Verify all profiles exist
        for tenant in tenants:
            tenant_profiles = self.profile_manager.list_profiles(tenant)
            self.assertEqual(len(tenant_profiles), 3)
            for profile in profiles:
                self.assertIn(profile, tenant_profiles)
        
        # Generate content and extract HRV
        content = self.writer.generate("Multi-tenant integration test")
        hrv_vector = self.extractor.extract(content)
        
        # Verify HRV extraction
        self.assertIsInstance(hrv_vector, list)
        self.assertEqual(len(hrv_vector), 8)
    
    def test_hrv_dimensions_consistency(self):
        """Test HRV dimensions consistency across components"""
        # Generate content
        content = self.writer.generate("HRV consistency test")
        
        # Extract HRV
        hrv_vector = self.extractor.extract(content)
        
        # Get API response
        request = SimpleRequest(prompt="HRV consistency test")
        response = hr_generate(request)
        
        # Verify all HRV vectors have correct dimensions
        self.assertEqual(len(hrv_vector), len(HRV_DIMENSIONS))
        self.assertEqual(len(response.hrv_feedback), len(HRV_DIMENSIONS))
        
        # Verify all values are numeric
        for value in hrv_vector:
            self.assertIsInstance(value, (int, float))
        
        for value in response.hrv_feedback:
            self.assertIsInstance(value, (int, float))
    
    def test_content_quality_integration(self):
        """Test content quality across integration"""
        prompts = [
            "Short prompt",
            "This is a medium length prompt with more details",
            "This is a very long prompt with extensive details and specific requirements for content generation testing"
        ]
        
        for prompt in prompts:
            # Generate content via writer
            writer_content = self.writer.generate(prompt)
            
            # Generate content via API
            request = SimpleRequest(prompt=prompt)
            api_response = hr_generate(request)
            
            # Extract HRV from both
            writer_hrv = self.extractor.extract(writer_content)
            
            # Verify all components work
            self.assertIsInstance(writer_content, str)
            self.assertIsInstance(api_response.article, str)
            self.assertIsInstance(writer_hrv, list)
            self.assertIsInstance(api_response.hrv_feedback, list)
            
            # Verify content contains prompt
            self.assertIn(prompt, writer_content)
            self.assertIn(prompt, api_response.article)
            
            # Verify HRV dimensions
            self.assertEqual(len(writer_hrv), 8)
            self.assertEqual(len(api_response.hrv_feedback), 8)
    
    def test_error_handling_integration(self):
        """Test error handling across integration"""
        # Test with empty prompt
        try:
            content = self.writer.generate("")
            hrv = self.extractor.extract(content)
            self.assertIsInstance(hrv, list)
        except Exception:
            # Should handle gracefully
            pass
        
        # Test API with empty prompt
        try:
            request = SimpleRequest(prompt="")
            response = hr_generate(request)
            self.assertIsInstance(response.article, str)
        except Exception:
            # Should handle gracefully
            pass
    
    def test_performance_integration(self):
        """Test performance across integrated components"""
        import time
        
        start_time = time.time()
        
        # Run multiple integrated operations
        for i in range(5):
            prompt = f"Performance test {i}"
            
            # Generate content
            content = self.writer.generate(prompt)
            
            # Extract HRV
            hrv = self.extractor.extract(content)
            
            # Save profile
            self.profile_manager.save_profile("perf_test", f"profile_{i}", hrv)
            
            # Load profile
            loaded_hrv = self.profile_manager.load_profile("perf_test", f"profile_{i}")
            
            # API call
            request = SimpleRequest(prompt=prompt)
            response = hr_generate(request)
            
            # Verify operations
            self.assertIsInstance(content, str)
            self.assertIsInstance(hrv, list)
            self.assertIsInstance(loaded_hrv, list)
            self.assertIsInstance(response.article, str)
        
        end_time = time.time()
        total_time = end_time - start_time
        
        # Should complete in reasonable time
        self.assertLess(total_time, 30.0)  # 30 seconds for 5 integrated operations
    
    def test_data_flow_integration(self):
        """Test data flow between components"""
        # Start with prompt
        prompt = "Data flow integration test"
        
        # Generate content
        content = self.writer.generate(prompt)
        
        # Extract HRV
        hrv = self.extractor.extract(content)
        
        # Save as profile
        self.profile_manager.save_profile("flow_test", "test_profile", hrv)
        
        # Load profile
        loaded_hrv = self.profile_manager.load_profile("flow_test", "test_profile")
        
        # Generate new content based on loaded profile
        new_content = self.writer.generate("New content with loaded profile")
        
        # Extract HRV from new content
        new_hrv = self.extractor.extract(new_content)
        
        # Verify data flow
        self.assertEqual(hrv, loaded_hrv)
        self.assertIsInstance(content, str)
        self.assertIsInstance(new_content, str)
        self.assertEqual(len(hrv), 8)
        self.assertEqual(len(new_hrv), 8)
        
        # Verify content contains prompts
        self.assertIn(prompt, content)
        self.assertIn("New content with loaded profile", new_content)
    
    def test_component_isolation(self):
        """Test that components can work independently"""
        # Test extractor alone
        test_text = "Independent test text"
        hrv = self.extractor.extract(test_text)
        self.assertIsInstance(hrv, list)
        self.assertEqual(len(hrv), 8)
        
        # Test writer alone
        content = self.writer.generate("Independent writer test")
        self.assertIsInstance(content, str)
        self.assertGreater(len(content), 0)
        
        # Test profile manager alone
        test_hrv = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
        self.profile_manager.save_profile("independent_test", "test_profile", test_hrv)
        loaded_hrv = self.profile_manager.load_profile("independent_test", "test_profile")
        self.assertEqual(loaded_hrv, test_hrv)
        
        # Test API alone
        request = SimpleRequest(prompt="Independent API test")
        response = hr_generate(request)
        self.assertIsInstance(response.article, str)
        self.assertIsInstance(response.hrv_feedback, list)


if __name__ == '__main__':
    unittest.main()
